import type { Metadata } from "next"; 
import "./globals.css";
import { Layout, Menu } from "antd";
import { Content, Footer, Header } from "antd/es/layout/layout";
import Link from "antd/es/typography/Link";
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const items = [
  { key: "home", label: <Link href={"/"}>Home</Link> },
  { key: "portfolios", label: <Link href={"/portfolios"}>Portfolios</Link> },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <Layout style={{minHeight: "100vh"}}>
            <Header>
            <Menu 
            theme="dark" 
            mode="horizontal" 
            items={items}  
            style={{flex: 1, minWidth:0 }}/> 
            </Header> 
            <Content style={{padding: "0 48px"}}>{children}</Content> 
            <Footer style={{textAlign: "center" }}>
              Portfolios created by Volkov
            </Footer>
            </Layout> 
            
         </body>
    </html>
  );
}
